#!/bin/bash

export PYTHONPATH="/var/www/spitzermicrolensing"
export DJANGO_SETTINGS_MODULE="mulens_tom.settings"

# collect static files
python /var/www/spitzermicrolensing/manage.py collectstatic --noinput

# perform database migrations
python /var/www/spitzermicrolensing/manage.py migrate --noinput

# run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
