# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_filter', models.CharField(choices=[('SDSS-i', 'SDSS-i'), ('SDSS-r', 'SDSS-r'), ('Pan-STARRS-Z', 'Pan-STARRS-Z'), ('Bessell-V', 'Bessell-V'), ('Bessell-R', 'Bessell-R'), ('Cousins-Ic', 'Cousins-Ic')], default='SDSS-i', max_length=15, verbose_name='Filter')),
                ('exp_time', models.FloatField(verbose_name='Exposure time')),
                ('n_exp', models.IntegerField(verbose_name='Number of exposures')),
                ('defocus', models.FloatField(blank=True, verbose_name='Defocus')),
                ('binning', models.IntegerField(blank=True, verbose_name='Binning')),
            ],
        ),
        migrations.CreateModel(
            name='PhotObs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=50, verbose_name='Group ID')),
                ('network', models.CharField(blank=True, max_length=50, verbose_name='Network')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='Site')),
                ('telescope', models.CharField(blank=True, max_length=50, verbose_name='Telescope')),
                ('instrument', models.CharField(blank=True, max_length=50, verbose_name='Instrument')),
                ('track_id', models.CharField(blank=True, max_length=100, verbose_name='Tracking ID')),
                ('start_obs', models.DateTimeField(blank=True, verbose_name='Start observing timestamp')),
                ('stop_obs', models.DateTimeField(blank=True, verbose_name='Stop observing timestamp')),
                ('cadence', models.FloatField(blank=True, verbose_name='Cadence')),
                ('jitter', models.FloatField(blank=True, verbose_name='Jitter')),
                ('group_type', models.CharField(blank=True, choices=[('single', 'Single'), ('cadence', 'Cadence')], default='single', max_length=10, verbose_name='Group Type')),
                ('obs_mode', models.CharField(blank=True, choices=[('override', 'Rapid reponse'), ('queue', 'Queue')], default='queue', max_length=30, verbose_name='Observation mode')),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('active', 'Active'), ('expired', 'Expired'), ('error', 'Error')], default='submitted', max_length=30, verbose_name='Observation status')),
                ('info', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Information')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('exposures', models.ManyToManyField(blank=True, to='tom.ExposureSet')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('proposal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proposal ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50, verbose_name='User handle')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('family_name', models.CharField(max_length=50, verbose_name='Family name')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Affiliation')),
                ('email', models.EmailField(max_length=254)),
                ('lco_observer_id', models.CharField(blank=True, max_length=50, verbose_name='LCO User ID')),
                ('lco_observer_pswd', models.CharField(blank=True, max_length=50, verbose_name='LCO User login')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=50, verbose_name='RA')),
                ('dec', models.CharField(max_length=50, verbose_name='Dec')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom.Project')),
                ('targets', models.ManyToManyField(blank=True, to='tom.Target')),
            ],
        ),
        migrations.CreateModel(
            name='TargetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom.Target')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, to='tom.ProjectUser'),
        ),
        migrations.AddField(
            model_name='photobs',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom.Project'),
        ),
        migrations.AddField(
            model_name='photobs',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom.Target'),
        ),
    ]
