# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photobs',
            old_name='info',
            new_name='information',
        ),
    ]
