# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0002_auto_20170501_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proposal ID'),
        ),
    ]
