# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0003_photobs_airmass_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='token',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token'),
        ),
    ]
