# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0003_project_proposal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photobs',
            old_name='obs_model',
            new_name='obs_mode',
        ),
    ]
