# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0004_auto_20170606_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='projects',
            field=models.ManyToManyField(blank=True, to='tom.Project'),
        ),
    ]
