# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0005_auto_20180112_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Name')),
                ('site', models.CharField(max_length=10, verbose_name='Site')),
                ('telescope', models.CharField(max_length=10, verbose_name='Telescope')),
                ('instrument', models.CharField(max_length=10, verbose_name='Instrument')),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='default_locations',
            field=models.ManyToManyField(blank=True, to='tom.ObservingFacility'),
        ),
    ]
