# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0006_auto_20180113_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observingfacility',
            options={'verbose_name_plural': 'observing facilities'},
        ),
        migrations.RenameField(
            model_name='observingfacility',
            old_name='code',
            new_name='name',
        ),
    ]
