# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0008_observingfacility_enclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
