# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0009_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobs',
            name='ipp',
            field=models.FloatField(blank=True, default=1.05, verbose_name='IPP'),
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_rapid',
            field=models.NullBooleanField(default=False),
        ),
    ]
