# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0010_auto_20180304_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobs',
            name='rapid_mode',
            field=models.NullBooleanField(default=False),
        ),
    ]
