# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0011_photobs_rapid_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobs',
            name='simulate',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photobs',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('active', 'Active'), ('expired', 'Expired'), ('error', 'Error'), ('simulated', 'Simulated')], default='submitted', max_length=30, verbose_name='Observation status'),
        ),
    ]
