# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-28 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0015_auto_20180925_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobs',
            name='lunar_distance_limit',
            field=models.FloatField(blank=True, default=10.0, verbose_name='Lunar distance limit'),
        ),
    ]
