# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0016_photobs_lunar_distance_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
