# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom', '0018_targetlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetlist',
            name='status',
        ),
    ]
